[mypy]
mypy_path = backend
files = backend/app
python_version = 3.13
strict = True
plugins = pydantic.mypy
warn_unused_ignores = True
disallow_untyped_defs = True
explicit_package_bases = True
exclude = alembic/versions

[mypy-alembic.*]
ignore_missing_imports = True